/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: "#FAF7F2",
        surface: "#FFFFFF",
        "surface-muted": "#F1ECE4",
        border: "#E7E1D6",
        "text-primary": "#211F1D",
        "text-secondary": "#726C63",
        "text-tertiary": "#A39C90",
        primary: "#372F73",
        "primary-foreground": "#FFFFFF",
        accent: "#FF6B4A",
        "accent-foreground": "#FFFFFF",
        "badge-flightstay-bg": "#E5E6FC",
        "badge-flightstay-fg": "#453CA9",
        "badge-villa-bg": "#E6F1E7",
        "badge-villa-fg": "#257535",
        "badge-experience-bg": "#FFEEE0",
        "badge-experience-fg": "#BE681D",
      },
      borderRadius: {
        card: "16px",
        badge: "6px",
        chip: "10px",
        "sheet-top": "24px",
        fab: "28px",
        bubble: "16px",
      },
      fontSize: {
        "crew-title": ["22px", { lineHeight: "130%", fontWeight: "700" }],
        "crew-heading": ["17px", { lineHeight: "130%", fontWeight: "600" }],
        "crew-body-strong": ["15px", { lineHeight: "140%", fontWeight: "600" }],
        "crew-body": ["15px", { lineHeight: "140%", fontWeight: "400" }],
        "crew-caption": ["13px", { lineHeight: "130%", fontWeight: "400" }],
        "crew-micro": ["11px", { lineHeight: "120%", fontWeight: "500" }],
      },
      fontFamily: {
        sans: ["Inter_400Regular"],
        "sans-medium": ["Inter_500Medium"],
        "sans-semibold": ["Inter_600SemiBold"],
        "sans-bold": ["Inter_700Bold"],
      },
    },
  },
  plugins: [],
};
